name: Playwright Tests
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PMTOOL_USERNAME: ${{ secrets.PMTOOL_USERNAME }}
      PMTOOL_PASSWORD: ${{ secrets.PMTOOL_PASSWORD }}
      TEGB_USER: ${{ secrets.TEGB_USER }}
      TEGB_PASSWORD: ${{ secrets.TEGB_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep=github-actions
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
